package com.example.comusenias.presentation.ui.theme

const val logoApp : String = "Logo de la app"
const val loginSuccess : String = "Login Success"
const val loginError : String = "Login Error"
const val emailText : String = "Correo electrónico"
const val password : String = "Contraseña"
const val confirmPassword: String = "Confirmar contraseña"
const val logIn : String = "Iniciar Sesion"
const val forgotPassword : String = "Olvide mi contraseña"
const val rememberMe : String = "Recuerdame"
const val orLoginWith : String = "o inicie sesión con"
const val signInWithGoogle : String = "Ingresa con Google"
const val invalidEmail : String = "Email invalido"
const val invalidPassword : String = "Password invalido"
const val dontHaveAccount: String = "No tienes cuenta?"
const val doYouAlreadyHaveAnAccount: String = "Ya tienes una cuenta?"
const val enter: String = "Ingresa"
const val register: String = "Registrate"
const val terms: String = "Terminos"
const val accept: String = "Acepto"
const val conditions: String = "Condiciones"
const val CHOSE_YOU_PROFILE = "ELEJI TU PERFIL"
const val CONTINUE = "Continuar"
const val ACEPT_TERMS = "Acepto  que mis datos sean utilizados con fines profesionales y de contacto."

const val logInLog = "Login"
const val email = "Email"
const val editData = "Editar Datos"
const val title = "Title"
const val arrowBack = "Arrow Back"
const val profile = "Perfil"
const val iconApp = "icono de la app"
const val iconButtonDescription = "icon button description"
const val insertDataToLogIn = "Ingrese los datos para iniciar sesión"
const val restrictionNameUserAccount = "El nombre de usuario debe tener al menos 3 caracteres"
const val restrictionPasswordUserAccount = "La contraseña debe tener al menos 8 caracteres"
const val passwordDoNotMatch = "Las contraseñas no coinciden"
const val emptyString = ""
const val LEAR_TEXT : String = "Aprender"
const val PROFILE_TEXT : String = "Perfil"
const val PREMIUM_TEXT : String = "Premium"
const val EMPTY_STRING : String = ""

/*-----------------DIALOG CAPTURE-----------------*/
const val DIALOG_GALLERY : String = "Galeria"
const val DIALOG_CAPTURE_PICTURE : String = "Tomar foto"
const val DIALOG_CAPTURE_TITLE : String = "Selecciona una opción"

/*-----------------CHANGE PROFILE CONTENT -----------------*/
const val CHANGE_PROFILE_USER = "Nuevo Usuario"
const val CHANGE_PROFILE_PASSWORD = "Nueva Contraseña"
const val CHANGE_PROFILE_CONFIRM_PASSWORD = "Confirmar Contraseña"

/*-----------------PROFILE CONTENT -----------------*/
const val PROFILE_USER = "Nombre del Usuario"
const val PROFILE_EMAIL = "Correo electrónico"
