package com.example.comusenias.presentation.ui.theme

const val logoApp: String = "Logo de la app"
const val loginSuccess: String = "Login Success"
const val loginError: String = "Login Error"
const val emailText: String = "Correo electrónico"
const val PASSWORD: String = "Contraseña"
const val confirmPassword: String = "Confirmar contraseña"
const val logIn: String = "Iniciar Sesion"
const val forgotPassword: String = "Olvide mi contraseña"
const val rememberMe: String = "Recuerdame"
const val orLoginWith: String = "o inicie sesión con"
const val signInWithGoogle: String = "Ingresa con Google"
const val invalidEmail: String = "Email invalido"
const val invalidPassword: String = "Password invalido"
const val dontHaveAccount: String = "No tienes cuenta?"
const val doYouAlreadyHaveAnAccount: String = "Ya tienes una cuenta?"
const val enter: String = "Ingresa"
const val REGISTER: String = "Registrarse"
const val REGISTER_TWO: String = "Registro"
const val ADD_DATA_FOR_REGISTER: String = "Ingresa los datos para registrarte"
const val terms: String = "Terminos"
const val accept: String = "Acepto"
const val conditions: String = "Condiciones"
const val CHOSE_YOU_PROFILE = "ELEGÍ TU PERFIL"
const val CONTINUE = "Continuar"
const val ACEPT_TERMS =
    "Acepto  que mis datos sean utilizados con fines profesionales y de contacto."
const val WHAT_IS_YOUR_NAME = "¿COMO TE LLAMAS?"
const val PROFESSIONAL_REGISTRATION = "Matricula"
const val NAME = "Nombre"
const val NUMBER_PHONE = "Telefono"
const val EXPIRY_OF_PROFESSIONAL_REGISTRATION = "Vencimiento de Matricula"
const val MEDICAL_TITLE = "Titulo Medico"
const val SPECIALTY = "Especialidad"
const val HOW_OLD_ARE_YOU = "¿CUANTOS  AŃOS TENES?"
const val AGE = "Edad"
const val CHILD = "Niño"
const val ESPECIALIST = "Especialista"
const val PROGRESS = "Tu Progreso"
const val CHECK_POINT = "Punto de Control"
const val CONSULT_WHIT_ESPECIALIST =
    "¿Has consultado con un especialista para evaluar cómo está avanzando tu aprendizaje?"
const val logInLog = "Login"
const val email = "Email"
const val editData = "Editar Datos"
const val title = "Title"
const val arrowBack = "Arrow Back"
const val iconApp = "icono de la app"
const val iconButtonDescription = "icon button description"
const val restrictionNameUserAccount = "El nombre de usuario debe tener al menos 3 caracteres"
const val restrictionPasswordUserAccount = "La contraseña debe tener al menos 8 caracteres"
const val passwordDoNotMatch = "Las contraseñas no coinciden"
const val emptyString = ""
const val SKIP: String = "Saltar"
const val IMAGE: String = "Imagen"
const val IMAGE_AVATAR: String = "image avatar"
const val IMAGE_EDIT_BUTTON: String = "image edit button"
const val LEAR_TEXT: String = "Aprender"
const val PROFILE_TEXT: String = "Perfil"
const val PREMIUM_TEXT: String = "Premium"
const val EMPTY_STRING: String = ""
const val START_WITH_LETTER: String = "Empecemos con la letra"
const val DESC_IMAGE_SIGN: String = "Descripción de la imagen"
const val CHOSE_CORRECT_SING: String = "Elegí la señal correcta"
const val FINISH_LVL: String = "!Felicitaciones! Nivel terminado"
const val GO_FOR_MORE: String = "Vamos por mas"
const val ID: String = "id"
const val LETTER: String = "letter"
const val LETTERS: String = "letras"
const val FIELD_IMAGES: String = "image"
const val PATH_IMAGE: String = "image/*"
const val VOWELS: String = "Vocales"
const val AVATAR: String = "Avatar"
const val HAVENT_ACCOUNT: String = "¿No tenes una cuenta?"
const val LOGIN_SUCCESS: String = "Acceso exitoso"
const val LOGIN_ERROR: String = "Acceso fallido"
const val SELECTED_IMAGE: String = "Selected Image"
const val UPDATE_DATA: String = "Actualizar Datos"
const val UPDATED_DATA: String = "Datos Actualizados"
const val ERROR_UPDATED_DATA: String = "Error al actualizar datos"
const val ERROR_UNKNOWN: String = "Error desconcido"
const val NAME_USER: String = "Nombre de usuario"
const val EMAIL: String = "Email"
const val LOG_IN: String = "Inicia Sesión"
const val DO_HAVE_ACCOUNT: String = "¿Ya tenes una cuenta?"
const val Y: String = "y"
const val CIRCLE_IMAGE: String = "Circle Image"
const val NAME_KID: String = "Nombre niño"
const val NUMBERS: String = "Números"
const val ROOT_GRAPH: String = "root_graph"
const val AUTH_GRAPH: String = "auth_graph"
const val HOME_GRAPH: String = "home_graph"
const val DETAILS_GRAPH: String = "details_graph"
const val Suscribe: String = "Suscribirse"
const val Suscribe_Ya: String = "Suscribete ahora y desbloque beneficios exclusivos"
const val Aviso: String = "AVISO"
const val NOMBRE_NOTIFICATION1: String = "Marcela te ha pedido que corrijas su ejercicio"
const val NOMBRE_NOTIFICATION2: String = "Natalia te ha pedido que corrijas su ejercicio"
const val NOMBRE_NOTIFICATION3: String = "Daniel te ha pedido que corrijas su ejercicio"
const val NOMBRE_NOTIFICATION4: String = "Nuevos desafios semanales disponibles. ¡Animate a practicar!"

/*-----------------DIALOG CAPTURE-----------------*/
const val DIALOG_GALLERY: String = "Galeria"
const val DIALOG_CAPTURE_PICTURE: String = "Tomar foto"
const val DIALOG_CAPTURE_TITLE: String = "Selecciona una opción"

/*-----------------CHANGE PROFILE CONTENT -----------------*/
const val CHANGE_PROFILE_USER = "Nuevo Usuario"
const val CHANGE_PROFILE_PASSWORD = "Nueva Contraseña"
const val CHANGE_PROFILE_CONFIRM_PASSWORD = "Confirmar Contraseña"

/*-----------------PROFILE CONTENT -----------------*/
const val PROFILE_USER = "Nombre del Usuario"
const val PROFILE_EMAIL = "Correo electrónico"

const val LETS_GO_LEARN: String = "¡Vamos aprender Sabrina!"