package com.ars.comusenias.presentation.ui.theme

const val logoApp: String = "Logo de la app"

/*-------------------POLICY-------------------*/
const val URL_TERMS_CONDITIONS: String =
    "https://vao-source-code.github.io/terms_and_conditions_comusenias/"
const val URL_POLICY_PRIVACY: String =
    "https://vao-source-code.github.io/policy-privacy-comusenias/"

/*-------------------LOGIN Y REGISTER-------------------*/
const val EMAIL_TEXT: String = "Email"
const val PASSWORD: String = "Contraseña"
const val CONFIRM_PASS: String = "Confirmar contraseña"
const val LOGIN: String = "Ingresar"
const val FORGOT_PASSWORD: String = "¿Olvidaste tu contraseña?"
const val INVALID_EMAIL: String = "Email invalido"
const val INVALID_PHONE: String = "Telefono invalido"
const val INVALID_DATE: String = "Fecha invalida"
const val invalidPassword: String = "Password invalido"
const val DONT_HAVE_ACCOUNT: String = "¿No tenés cuenta?"
const val DO_YOU_ALREADY_HAVE_AN_ACCOUNT: String = "¿Ya tenés cuenta?"
const val REGISTER: String = "Regístrate"
const val RESTRICTION_NAME_USER_ACCOUNT = "El nombre de usuario debe tener al menos 3 caracteres"
const val RESTRICTION_SPECIALIST_ACCOUNT = "Especialidad invalidad"
const val RESTRICTION_TITLE_MEDICAL_ACCOUNT = "Especialidad invalidad"
const val RESTRICTION_PASSWORD_USER_ACCOUNT = "Contraseña: Mín. 8 caracteres, 1 mayúscula, 1 número"
const val TERMS: String = "Terminos"
const val ACCEPT: String = "Acepto"
const val CONDITIONS: String = "Condiciones"
const val CONTINUE = "Continuar"
const val PROFESSIONAL_REGISTRATION = "Matricula"
const val COMPLETE_NAME = "Nombre completo"
const val NUMBER_PHONE = "Telefono"
const val EXPIRY_OF_PROFESSIONAL_REGISTRATION = "Vencimiento"
const val MEDICAL_TITLE = "Titulo Medico"
const val SPECIALTY = "Especialidad"
const val ESPECIALIST = "Especialista"
const val HAVENT_ACCOUNT: String = "¿No tenés una cuenta?"
const val RESET_PASSWORD_SUCCESS: String = "Reseteo exitoso, revise la casilla de email"
const val LOGIN_ERROR: String = "Acceso fallido"
const val REGISTER_ERROR: String = "Error al registrarse"
const val RESET_PASSWORD_ERROR: String = "Error al resetear la contraseña"
const val BIRTHDAY: String = "Fecha de Nacimiento"
const val OBSERVATIONS_ERROR: String = "Error al cargar las observaciones"
const val OBSERVATION_ERROR: String = "Error al cargar la observación"
const val LOADING_ERROR: String = "Error de Carga"
const val SUCCESS: String = "Generado con éxito"
const val TEXT_TITLE_RESET_PASSWORD: String = "Reestablecer contraseña"
const val TEXT_RESET_PASSWORD: String =
    "Introduce tu correo electrónico y te enviaremos instrucciones para restablecer tu contraseña "
const val BUTTON_RESET_PASSWORD: String = "Enviar"
const val CREATE_ACCOUNT: String = "Crear cuenta"
const val BEGINNER = "Principiante"
const val INTERMEDIATE = "Intermedio"
const val ADVANCED = "Avanzado"

const val LEVEL_SELECTION_TITLE = "Para empezar"
const val LEVEL_SELECTION_SUBTITLE = "Elige tu nivel"
const val LEVEL_SELECTION_DESCRIPTION =
    "Podrás cambiar de nivel cuando gustes \no iniciar nuevamente con otro nivel"


/*-------------------HOMECHILDREN-------------------*/
const val WELCOME = "Te damos la bienvenida"
const val PROGRESS = "Tu Progreso"
const val CHECK_POINT = "Punto de Control"
const val CONSULT_WHIT_ESPECIALIST =
    "¿Has consultado con un especialista para evaluar cómo está avanzando tu aprendizaje?"
const val ARROWBACK = "Arrow Back"
const val ICONAPP = "icono de la app"
const val ICON_BUTTON_DESCRIPTION = "icon button description"
const val SEND = "Enviar"
const val OBSERVATION = "Observación"
const val OBSERVATIONS = "Observaciones"
const val PROGRESS_GAME = "Progreso"
const val PASSWORD_DO_NOT_MATCH = "Las contraseñas no coinciden"
const val ADD_PATIENT = "Agregar paciente"
const val ENTER: String = "Ingresa"
const val SKIP: String = "Saltar"
const val RETRY: String = "REINTENTAR"
const val IMAGEN: String = "Imagen"
const val IMAGE_AVATAR: String = "image avatar"
const val IMAGE_EDIT_BUTTON: String = "image edit button"
const val LEAR_TEXT: String = "Aprender"
const val PROFILE_TEXT: String = "Perfil"
const val PREMIUM_TEXT: String = "Premium"
const val SUPPORT_TEXT: String = "Soporte"
const val EMPTY_STRING: String = ""
const val LETTER: String = "letter"
const val FIELD_IMAGES: String = "image"
const val PATH_IMAGE: String = "image/*"
const val AVATAR: String = "Avatar"
const val SELECTED_IMAGE: String = "Selected Image"
const val UPDATE_DATA: String = "Actualizar Datos"
const val LOGOUT: String = "Desloguearse"
const val UPDATED_DATA: String = "Datos Actualizados"
const val ERROR_UPDATED_DATA: String = "Error al actualizar datos"
const val ERROR_UNKNOWN: String = "Error desconocido"
const val ERROR_LECTOR_QR: String = "Error al leer el QR"
const val NOT_RESPONSE_SUB_LEVEL: String = "No se encontro el Sub Nivel deseado"
const val LETS_GO: String = "Comencemos"
const val LOG_IN: String = "Inicia Sesión"
const val DO_HAVE_ACCOUNT: String = "¿Ya tienes una cuenta?"
const val Y: String = "y"
const val ROOT_GRAPH: String = "root_graph"
const val AUTH_GRAPH: String = "auth_graph"
const val HOME_GRAPH: String = "home_graph"
const val DETAILS_GRAPH: String = "details_graph"
const val SUBSCRIBE: String = "Suscribirse"
const val SUBSCRIBE_NOW: String = "Suscribete ahora y desbloque beneficios exclusivos"
const val WARNING: String = "AVISO"
const val CORRECT: String = "CORRECTAS"
const val INCORRECT: String = "INCORRECTAS"
const val CHOICES: String = "INTENTOS"

/*-------------------NOTIFICATION-------------------*/
const val NOMBRE_NOTIFICATION1: String = "Marcela te ha pedido que corrijas su ejercicio"
const val NOMBRE_NOTIFICATION2: String = "Natalia te ha pedido que corrijas su ejercicio"
const val NOMBRE_NOTIFICATION3: String = "Daniel te ha pedido que corrijas su ejercicio"
const val NOMBRE_NOTIFICATION4: String =
    "Nuevos desafios semanales disponibles. ¡Animate a practicar!"
const val CONGRATS_TEXT: String = "¡Superaste la lección, vamos por mas!"
const val ERROR_CONGRATS_TEXT: String = "Ups ¡Probemos de nuevo!"

const val THE_SIGN_IS: String = "La seña es..."
const val FINISH: String = "Finalizar"
const val WHAT_SIGN_IS: String = "¿Que seña es...?"
const val WHAT_LETTER_IS: String = "¿Que palabra es... ?"
const val ICON: String = "Icon"
const val PATIENTS: String = "Pacientes"
const val ERROR_RETRY_LEVEL: String = "Error al cargar el nivel"
const val ERROR_RETRY_SUB_LEVEL: String = "Error al cargar el sub nivel"
const val SUB_LEVEL: String = "subLevel"
const val DONT_YOU_HAVE_PATIENTS: String = "Aun no tenés pacientes."
const val SUB_LEVEL_TABLE: String = "subLevel_table"
const val SUB_LEVEL_ID: String = "idSubLevel"
const val STATUS: String = "status"
const val IMAGE_JPEG: String = "image/jpeg"
const val UNRECOGNIZED_DELEGATE: String = "Unrecognized delegate:"
const val ERROR_NOT_RECOGNIZE_VIDEO_FILE: String =
    "ResultBundle could not be returned in recognizeVideoFile"
const val ERROR_NOT_RESPONSE_VIDEO: String =
    "Frame at specified time could not be retrieved when recognition in video."
const val ERROR_NOT_USING_RUNNING_MODE_IMAGE: String =
    "Attempting to call detectImage while not using RunningMode.IMAGE"
const val UNKNOWN_ERROR: String = "An unknown error has occurred"

/*-------------------TASK MODEL-------------------*/
const val TASK_ALPHABET = "alphabet.task"
const val TASK_DAYS_OF_WEEKS = "daysOfWeeks.task"
const val TASK_MONTH = "month.task"
const val TASK_FAMILY = "family.task"
const val TASK_COLORS = "colors.task"
const val TASK_OPPOSITES = "opposites.task"
const val TASK_ZODIACS_SIGN = "zodiacsigns.task"
const val TASK_WORDS_OF_CORTESY_ONE = "wordsOfCourtesyPtOne.task"
const val TASK_WORDS_OF_CORTESY_TWO = "wordsOfCourtesyPtTwo.task"




const val MP_RECOGNIZER_FACE = "face_landmarker.task"
const val MP_RECOGNIZER_POSE = "pose_landmarker_heavy.task"
const val MP_RECOGNIZER_WORDS_TASK = "gesture_recognizer_three.task"
const val DATE_CAPTURE_FORMAT = "yyyy-MM-dd-HH-mm-ss-SSS"
const val PICTURE_CAMERA_IMAGES = "Pictures/My-Camera-App-Images"
const val UTF_8 = "UTF-8"
const val ERROR_TAKE_PICTURE = "Ocurrió un error al sacar la imagen."
const val ERROR_BINDING_CAMERA = "Error binding camera preview"
const val SHOW_CAMERA_PREVIEW = "showCameraPreview"


const val START_RECORD_VIDEO = "Video capture Start"
const val SUCCESS_RECORD_VIDEO = "Video Success"
const val FAILED_RECORD_VIDEO = "Video capture Failed"

const val IMAGE_SIGN: String = "imagen de seña"
const val ERROR_STOPPING_CAMERA = "Error stopping camera preview"
const val TLS = "TLS"
const val PROCESSING_VOWELS = "/processing_vowels"
const val FINISH_IN = "Termina en:"
const val NONE = "none"
const val MULTI_PART_FROM_DATA = "multipart/form-data"
const val KEY_BOOLEAN = "key_boolean"
const val TAKE_PHOTO = "Sacar foto"
const val GALLERY_SCREEN = "GalleryScreen"
const val CHILD_FILE = "image.jpg"
const val ERROR_TAKE_PHOTO = "Error al cargar la imagen desde URI:"
const val COMPLETED_LESSONS = "lecciones completadas"
const val INFO_TEXT_OPEN_CAMERA =
    "La cámara se abrirá para detectar tu lengua de señas.Tendrás 5 segundos para realizar el gesto.¡Prepárate!"
const val TITLE_DIALOG_PERMISSION = "Se requiere acceso a la cámara para continuar"
const val DESCRIPTION_DIALOG_PERMISSION =
    "Esta funcionalidad nos permite ofrecerte una experiencia más interactiva y enriquecedora."
const val CONFIG_PERMISSION = "Configurar permisos"
const val PACKAGE = "package"
const val PAYMENT_METHODS = "Medios de pago"
const val I_WANT_TO_SUSCRIBE = "Quiero suscribirme"
const val SUSCRIBER = "¡Suscribíte al nivel premium por un precio único!"
const val PRICE_SUSCRIBER = "$ 1.500 / mes"
const val EXPERIENCE_COMPLETED = "Accede a la experiencia completa"
const val PREMIUM_ONE_TITLE = "Acceso a todas las lecciones"
const val PREMIUM_ONE_DESCRIPTION = "Elige tus lecciones para un aprendizaje personalizado."
const val PREMIUM_TWO_TITLE = "Seguimiento personalizado"
const val PREMIUM_TWO_DESCRIPTION =
    "Conta con el seguimiento de un profesional para maximizar tu aprendizaje."
const val PREMIUM_THREE_TITLE = "Sin anuncios"
const val PREMIUM_THREE_DESCRIPTION = "Evita las interrupciones."
const val PREMIUM_FOUR_TITLE = "Contenidos Premium exclusivos"
const val SHOW_LAZY_COLUMN_TAG = "ShowLazyColumnTag"
const val PREMIUM_FOUR_DESCRIPTION = "Amplía tu vocabulario con lecciones y cursos especializados."
const val ID = "id"
const val DATE_OBSERVATION = "dateObservation"
const val ID_SPECIALIST = "idSpecialist"
const val ID_CHILDREN = "idChildren"
const val OBSERVATION_CHILDREN = "observation"
const val ERROR_SCAN_QR = "Error al leer el cdigo QR"
const val NAME = "name"
const val IMAGE = "image"
const val DATE = "date"
const val TEL = "tel"
const val MEDICAL_LICENSE = "medicalLicense"
const val SPECIALITY = "speciality"
const val TITLE_MEDICAL = "titleMedical"
const val MEDICAL_LICENSE_EXPIRATION = "medicalLicenseExpiration"
const val DISCULPA = "Disculpa"
const val PERMISO = "Permiso"

/*-----------------BUTTONS AND ICONS-----------------*/
const val CLOSE: String = "Salir de la pantalla"

/*-----------------DIALOG CAPTURE-----------------*/
const val DIALOG_GALLERY: String = "Galeria"
const val DIALOG_CAPTURE_PICTURE: String = "Tomar foto"
const val DIALOG_CAPTURE_TITLE: String = "Selecciona una opción"

/*-----------------CHANGE PROFILE CONTENT -----------------*/
const val CHANGE_PROFILE_USER = "Nuevo Usuario"
const val CHANGE_PROFILE_PASSWORD = "Nueva Contraseña"
const val CHANGE_PROFILE_CONFIRM_PASSWORD = "Confirmar Contraseña"
const val CHANGE_TITLE_MEDICY = "Titulo Medico"
const val CHANGE_SPECIALIST_MEDICY = "Especialidad"

/*-----------------PROFILE CONTENT -----------------*/
const val PROFILE_USER = "Nombre del Usuario"
const val PROFILE_EMAIL = "Correo electrónico"
const val PROFILE_NAME_SURNAME = "Nombre y Apellido"
const val PROFILE_BIRTHDATE = "Fecha Nacimiento"

/*-----------------QR -----------------*/
const val QR_SCAN = "Escanear QR"
const val QR_SCAN_TEXT_CHILDREN = "Escanea el QR del niño para agregarlo a tu lista de pacientes"
const val PRESS_THE_QR_BUTTON = "Aprieta el botón QR"
const val QR_ADD = "Agregar"

/*-----------------Pasaje datos -----------------*/
const val PACIENT = "pacient"
const val CHILDREN_OBSERVATION = "observation"
const val SPECIALIST_PROFILE = "specialist_profile"